version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    restart: unless-stopped
    ports:
      - "3000:80"
    # stdin_open: true
    # tty: true
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - /app/node_modules
    restart: unless-stopped
    env_file:
      - ./api/.env
    user: "1000:1000"  
    depends_on:
      - database
  database:
    image: mongo:4.4.10
    volumes:
      - ./api/.docker/data/database:/data/db
    restart: unless-stopped
